version = 0.1
[default.deploy.parameters]
stack_name = "RaspTempToApi"
resolve_s3 = true
s3_prefix = "RaspTempToApi"
region = "ap-northeast-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
