AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 10
    Runtime: python3.9
    Environment:
      Variables:
        TABLE_NAME: !Ref EnvironmentDataTable

Resources:
  EnvironmentDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: EnvironmentData
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  EnvironmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: environment-data
      Description: 환경 데이터 처리
      CodeUri: ./lambda
      Handler: app.handler
      Events:
        PostEnvironmentApi:
          Type: Api
          Properties:
            Path: /environment
            Method: POST
        GetEnvironmentApi:
          Type: Api
          Properties:
            Path: /environment
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EnvironmentDataTable

Outputs:
  ApiUrl:
    Description: "POST/GET /environment"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
